-- Seed data for counties.
USE yek;

INSERT INTO counties (code, name, capital) VALUES
('001', 'Mombasa', 'Mombasa'),
('002', 'Kwale', 'Kwale'),
('003', 'Kilifi', 'Kilifi'),
('004', 'Tana River', 'Hola'),
('005', 'Lamu', 'Lamu'),
('006', 'Taita-Taveta', 'Mwatate'),
('007', 'Garissa', 'Garissa'),
('008', 'Wajir', 'Wajir'),
('009', 'Mandera', 'Mandera'),
('010', 'Marsabit', 'Marsabit'),
('011', 'Isiolo', 'Isiolo'),
('012', 'Meru', 'Meru'),
('013', 'Tharaka-Nithi', 'Kathwana'),
('014', 'Embu', 'Embu'),
('015', 'Kitui', 'Kitui'),
('016', 'Machakos', 'Machakos'),
('017', 'Makueni', 'Wote'),
('018', 'Nyandarua', 'Ol Kalou'),
('019', 'Nyeri', 'Nyeri'),
('020', 'Kirinyaga', 'Kerugoya'),
('021', 'Murang''a', 'Murang''a'),
('022', 'Kiambu', 'Kiambu'),
('023', 'Turkana', 'Lodwar'),
('024', 'West Pokot', 'Kapenguria'),
('025', 'Samburu', 'Maralal'),
('026', 'Trans Nzoia', 'Kitale'),
('027', 'Uasin Gishu', 'Eldoret'),
('028', 'Elgeyo-Marakwet', 'Iten'),
('029', 'Nandi', 'Kapsabet'),
('030', 'Baringo', 'Kabarnet'),
('031', 'Laikipia', 'Nanyuki'),
('032', 'Nakuru', 'Nakuru'),
('033', 'Narok', 'Narok'),
('034', 'Kajiado', 'Kajiado'),
('035', 'Kericho', 'Kericho'),
('036', 'Bomet', 'Bomet'),
('037', 'Kakamega', 'Kakamega'),
('038', 'Vihiga', 'Mbale'),
('039', 'Bungoma', 'Bungoma'),
('040', 'Busia', 'Busia'),
('041', 'Siaya', 'Siaya'),
('042', 'Kisumu', 'Kisumu'),
('043', 'Homa Bay', 'Homa Bay'),
('044', 'Migori', 'Migori'),
('045', 'Kisii', 'Kisii'),
('046', 'Nyamira', 'Nyamira'),
('047', 'Nairobi City', 'Nairobi');

